### ISSUE TITLE
bot stop working

### ISSUE THREAD

**Issue by asdasd888** [AchmadFathoni/Duellink-PC-Bot#12]
![rthrth](https://user-images.githubusercontent.com/7657198/34466451-f89c8dd6-ef05-11e7-991a-16c5071f9fb1.jpg)
![sssssssss](https://user-images.githubusercontent.com/7657198/34466449-f44351c0-ef05-11e7-96c1-f06d84a9f707.jpg)

when pvp notification and no network connection detected bot will stop working.

**Comment by StoKerz** [comment]
Bot work only PvE
