### ISSUE TITLE
Request - Same bot without "Autowin cheat"

### ISSUE THREAD

**Issue by joelcancela** [AchmadFathoni/Duellink-PC-Bot#18]
Your bot is really useful and thank you for that ! 
But if we could have a version that works without the "Autowin cheat" (which is bannable) that would be so cool, what do you think about that ? 😄

**Comment by ftuyama** [comment]
Hello @joelcancela, I implemented this behavior in the PR https://github.com/AchmadFathoni/Duellink-PC-Bot/pull/19, maybe you'd like to check it out.

**Comment by joelcancela** [comment]
I definitely will, thank you :)
