### ISSUE TITLE
bug vegabond

### ISSUE THREAD

**Issue by asdasd888** [AchmadFathoni/Duellink-PC-Bot#3]
![1](https://user-images.githubusercontent.com/7657198/34447984-fdeb46c4-ed1b-11e7-8dc2-90dbd6f77f2f.jpg)
bot click Light and go to Battle city

**Comment by AchmadFathoni** [comment]
@asdasd888 Is newest commit still produce the issue?

**Comment by asdasd888** [comment]
no
